language: python
matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=py36 LD_LIBRARY_PATH=$HOME/.camoco/lib:$LD_LIBRARY_PATH PATH=$HOME/.camoco/bin:$HOME/.camoco/conda/bin:$PATH PIP_USER=FALSE

# Install packages
install:
  - pip install pytest-cov numpy Cython
  - pip install git+git://github.com/LinkageIO/Minus80.git
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - which py.test
  - cd tests
  - py.test -v --cov=camoco --cov-config coveragerc
after_success:
    - coveralls
