language: python
matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=py36 LD_LIBRARY_PATH=$HOME/.camoco/lib:$LD_LIBRARY_PATH PATH=$HOME/.camoco/bin:$HOME/.camoco/conda/bin:$PATH PIP_USER=FALSE

# Install packages
install:
  # Install MCL
  - wget http://micans.org/mcl/src/mcl-latest.tar.gz
  - tar xzf mcl-latest.tar.gz
  - cd $(find . -name 'mcl-*' -type d | head -n 1)
  - ./configure
  - make
  - make install 
  - cd ..
  # Install Camoco
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - pip install pytest-cov
  - which py.test
  - cd tests
  - py.test -v --cov=camoco --cov-config coveragerc
after_success:
    - coveralls
